# syntax version.
version: "3.9"

services:
  web:
    image: nginx:latest
    container_name: web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites/:/etc/nginx/sites-available:ro
      - ./storage/nginx:/var/log/nginx
#      - ./nginx/config/qmyx.conf:/etc/nginx/conf.d/qmyx.conf:ro
      #- "./nginx/ssl:/etc/ssl"
#      - "/mnt/d/wamp/www/qmyx-base:/usr/share/nginx/html/qmyx-base" #需要修改为你项目的目录
    ports:
      - "80:80"  # api http
      - "443:443" # api https
    restart: always
    depends_on:
      - ticket
    networks:
      - default

  mysql:
    platform: linux/x86_64
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ticket
    networks:
      - default
    volumes:
      - ./storage/mysql:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:5.0.9-buster
    ports:
      - 6379:6379
    stdin_open: true
    tty: true
    networks:
      - default

  ticket:
    build:
      context: ./docker/php
    container_name: ticket
    volumes:
      - ./:/app
    tty: true
    networks:
      - default

networks:
  default:
    name: octane-backend
    driver: bridge

